name: Formatting

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - 'migrations/**'
      - 'scripts/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/workflows/**'
      - 'migrations/**'
      - 'scripts/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Check Formatting
        run: |
          rustup component add rustfmt
          cargo fmt -- --check