name: Build Test Lint

on:
  push:
    branches: [ release ]
    paths-ignore:
      - '.github/workflows/**'
      - 'migrations/**'
      - 'scripts/**'
  #    paths:
  #      - none

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check Formatting
        run: |
          rustup component add rustfmt
          cargo fmt -- --check

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Database
        run: bash scripts/init_db.sh

      - name: Build Release
        run: cargo build --release

      - name: Run tests
        run: cargo test --verbose

      - name: Check Linting
        run: cargo clippy --target-dir=target/release -- -D warnings

  deploy:
    runs-on: ubuntu-latest
    needs: [ build, format]

    steps:
      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PI_HOST }}
          username: ${{ secrets.PI_USER }}
          key: ${{ secrets.PI_SSH_KEY }}
          script: |
            cd /path/to/your/project
            git pull
            ./deploy_script.sh